[[language]]
name = "bash"
auto-format = true
language-servers = ["bash-language-server"]

[[language]]
name = "c"
auto-format = true
language-servers = ["clangd"]

[[language]]
name = "cpp"
auto-format = true
language-servers = ["clangd"]

[[language]]
name = "prisma"
auto-format = true
language-servers = ["prisma-language-server"]

[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["ruff", "pyright"]

[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["rust-analyzer"]

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "javascript"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["typescript-language-server"]


[[language]]
name = "typescript"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["typescript-language-server"]

# -----------------------------------------------------------------------

[language-server]
prisma-language-server = { command = "prisma-language-server", args = [
  "--stdio",
], config = { prisma = { enableDiagnostics = true } } }

[language-server.bash-language-server]
command = "bash-language-server"

[language-server.clangd]
command = "clangd"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.typescript-language-server]
command = "typescript-language-server"
